# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r:
- oldrel
- release
- devel

r_packages:
- tidyverse
- vegan

bioc_packages:
- BiocInstaller

r_github_packages:
- joey711/phyloseq
- grunwaldlab/metacoder
- ropensci/taxa
- MadsAlbertsen/ampvis2

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
